Feat/119 : 친구추가 프로필조회 기능 api
it-s-time-dev/backend pull request #122
Opened 2024-07-06 10:27 UTC by bangyewon

<img width="1082" alt="스크린샷 2024-07-05 오후 7 01 04" src="https://github.com/it-s-time-dev/backend/assets/90364660/c3276cc2-72fe-4cd5-bb52-3a571e3632ac">

2024-07-06 10:29 UTC, bangyewon commented on src/main/java/Itstime/planear/member/domain/Member.java
@OneToMany를 삭제하고 다른 방법으로 연결하고 싶은데 어떤 식으로 해야할지 고민중입니다 ...

2024-07-07 08:28 UTC, be-student requested changes

2024-07-07 08:28 UTC, be-student commented on src/main/java/Itstime/planear/member/domain/Member.java
편의를 위해서 OneToMAny 써도 되긴 하는데, 지금 구조상 양방향 의존성이 생겨서, 그 부분만큼은 피해주면 좋을 것 같아
연관관계를 굳이 안 맺고, WearingRepository.findAllByMemberId() 를 통해서 조회하는 방향으로 틀 수도 있을거야

2024-07-07 11:44 UTC, hyeon-gyu approved these changes

2024-07-08 12:17 UTC, be-student approved these changes
고생 많았어!

2024-07-08 12:18 UTC, merged